# Generated by Django 4.0.2 on 2022-02-22 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='MainCategory')),
                ('info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='subCategory')),
                ('info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Product')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Product')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Product')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Product')),
                ('og_price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('discounted_price', models.IntegerField(default=0)),
                ('sell_price', models.IntegerField(default=0)),
                ('info', models.TextField()),
                ('status', models.CharField(choices=[('New-Arrival', 'New-Arrival'), ('Out-of-Stock', 'Out-of-Stock')], default='New-Arrival', max_length=200)),
                ('total_price', models.IntegerField(default=0)),
                ('mcate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.maincategorymodel')),
                ('scate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subcategorymodel')),
            ],
        ),
    ]
