# Generated by Django 4.0.2 on 2022-03-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
