# Generated by Django 4.0.2 on 2022-04-20 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
